# Generated by Django 6.1.1 on 2026-09-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_remove_note_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='NOTE',
        ),
    ]
